export const SET_USER_LOGIN = "SET_USER_LOGIN";
export const SET_USER_LOGIN_SUCCESS = "SET_USER_LOGIN_SUCCESS";
export const SET_USER_LOGIN_FAIL = "SET_USER_LOGIN_FAIL";
export const SET_USER_LOGOUT = "SET_USER_LOGOUT";

export const GET_DAY_WORD = "GET_DAY_WORD";
export const SET_DAILY_WORD = "SET_DAILY_WORD";

export const SET_NEXT_PAGE = "SET_NEXT_PAGE";
export const RESET_NEXT_PAGE = "RESET_NEXT_PAGE";