export default {
  // font-size
  FONT_SIZE_SUPER_SMALL: 12,
  FONT_SIZE_SMALL: 15,
  FONT_SIZE_MEDIUM: 17,
  FONT_SIZE_LARGE: 20,
  FONT_SIZE_SUPER_LARGE: 25,
  FONT_SIZE_EXTREME_LARGE: 35,
  // font-weight
  FONT_WEIGHT_MEDIUM: "400",
  FONT_WEIGHT_HEAVY: "700",
  //font-color
  PRIMARY_COLOR_DEFAULT: "#00B4B4",
  PRIMARY_COLOR_PRESS: "#007E7E",
  PRIMARY_COLOR_DISABLE: "#96CACA",
  SECONDARY_COLOR_DEFAULT: "#C48148",
  SECONDARY_COLOR_PRESS: "#895A32",
  SECONDARY_COLOR_DISABLE: "#E4CAB3",

  COLOR_WHITE: "#FFFFFF",
  BACKGROUND_COLOR_1: "#FFFFFF",
  BACKGROUND_COLOR_2: "#F1EFE5",
  MODAL_BACKGROUND_COLOR: "rgba(0, 0, 0, 0.6)",
  SLIDER_BACKGROUND_COLOR: "rgba(60, 60, 67, 0.18)",
  LINE_COLOR: "rgba(60, 60, 67, 0.36)",
  FONT_COLOR_GRAY: "#828282",
  FONT_COLOR_GRAY4: "#BDBDBD",
  BORDER_COLOR: "rgba(79, 79, 79, 0.5)",
  FACEBOOK_COLOR: "#348BFC",
  FACEBOOK_COLOR_PRESS: '#307ee3',
};
